site_name: EXANTE Sales Simulator

docs_dir: docs
site_dir: ../docs

nav:
  - Product Vision: index.md
  - Architecture: architecture.md
  - What I'm not doing: scope.md
  - Questions & Assumptions: questions.md

theme:
  name: mkdocs